### ISSUE TITLE
Playable SCP Suggestion

### ISSUE THREAD

**Issue by DinoNuggets2** [joker-119/CustomRoles#15]
Just a suggestion, make it so at the beginning of a round, SCP-049 can randomly be replaced with SCP-035. 035 will be able a tutorial class and have a normal inventory. He can start with configurable items, like a zone manager, or enough to get to SCP-914 and get weapons. He is on the same team as SCPs, but kills everything else.

**Comment by joker-119** [comment]
I already have my own version of SCP-035, I just need permission from the person who commissioned it to include it in CustomRoles, and it's much better than your suggestion here imo. I will ask.
