### ISSUE TITLE
Custom Class tag dosen't dissapear after dying

### ISSUE THREAD

**Issue by DinoNuggets2** [joker-119/CustomRoles#16]
**Describe the bug**
When a Custom Roles player dies and respawns, they still have that same tag

**To Reproduce**
1. Become a random CustomRole
2. Die in any way
3. Respawn and have another player hover over you

**Expected behavior**
Expecting the players custom role tag to disappear after dying

**Server logs**
Not sure if I need this part for a bug like this or not

**EXILED Version ("latest" is not a version):**
4.1.6

**Results of `show plugins` command in console:**
Total: 33
Enabled: 29
Disabled: 4

**Additional context**

**Comment by joker-119** [comment]
Server logs and the full output of `show plugins` is requested for version and error verification, please add them (use pastebin don't just copy/paste the entire contents of either into a comment please) to this issue and include them in future ones, however I will take a look now and see if I can see something obvious.
